### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by nilcm10** [aspitaleri/gmxpbsa#1]
Hello! Would it be possible to have some examples/test cases? To check typical inputs and outputs, thus knowing what to expect. Thanks :)

**Comment by Bilal0101-debug** [comment]
Hello
While running GMXPBSA.Its giving this error
/Softwares/aetq_v1_1/final_GMXPBSAtool/GMXPBSAtool/gmxpbsa0.sh: line 290: /usr/local/gromacs/trjconv: No such file or directory
 Even though after setting the path.

**Comment by namus** [comment]
> Hello! Would it be possible to have some examples/test cases? To check typical inputs and outputs, thus knowing what to expect. Thanks :)

This might help: https://github.com/aspitaleri/gmxpbsa_demo
